# Generated by Django 4.1.5 on 2023-01-27 09:14

import api.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0002_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=api.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', api.fields.OrderField(blank=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
